### ISSUE TITLE
Small items todo

### ISSUE THREAD

**Issue by AnthonyLloyd** [haf/expecto#306]
- [x] Remove first lines of stack trace inside Expecto (and my directory)
- [x] Make expected: in green and actual: in red
- [x] need to red or green when it is longer
- [x] -h -? /? for help cmd line
- [x] printfn has that weird iterator problem
- [x] Order failed tests by test order (since tests order indicates which is root cause)
- [x] Look at System,Diagnostics.StackTrace to get line numbers instead of Cecil. (result; no good in F#)
- [x] Sort out colours for 16. Try the both way below.
- [x] config docs

**Comment by haf** [comment]
Let's not bring colors back to 16. Why?

**Comment by AnthonyLloyd** [comment]
It's just if I can't work out if the console supports it then the consoles that don't won't get any colour. Do you know of a way to do this?

**Comment by AnthonyLloyd** [comment]
One possible crazy way to do it without needing to know would be to set the 16 colour then 256 colour each time and reset in a similar way.

**Comment by haf** [comment]
I don't know of a console that only supports 16 colours. Which one are we talking about?

**Comment by AnthonyLloyd** [comment]
#305

**Comment by AnthonyLloyd** [comment]
Added a colours config (0,8 or 256). The 8 then 256 doesn't work.
Neither appveyor or travis really work with 256.
Decided to go with the config option.

**Comment by jzabroski** [comment]
What does MSBuild do?  I think it supported ANSI colors.

See this interesting thread I found while searching MSBuild: https://github.com/Microsoft/msbuild/pull/1827
